import { DomeModel } from "../core/types";
import { sub, cross, normalize } from "../core/math";

/**
 * Exports the dome faces as a 3D Wavefront OBJ file.
 */
export function exportDomeOBJ(model: DomeModel): string {
  const lines: string[] = [];

  lines.push("# Geodesic Dome CAD Export");
  lines.push("# Generated by KupolGeo Core v0.1");
  lines.push(`# Frequency: ${model.parameters.frequency}V, Diameter: ${model.parameters.diameter} mm, Height: ${model.parameters.height} mm`);
  lines.push(`# Vertices: ${model.nodes.length}, Beams: ${model.edges.length}, Faces: ${model.faces.length}`);
  lines.push("# Units: Millimeters (mm)");
  lines.push("");

  // Group: Vertices
  lines.push("g Dome_Vertices");
  for (const node of model.nodes) {
    const { x, y, z } = node.position;
    lines.push(`v ${x.toFixed(3)} ${y.toFixed(3)} ${z.toFixed(3)}`);
  }
  lines.push("");

  // Group: Normals
  lines.push("g Dome_Normals");
  for (const face of model.faces) {
    const pA = model.nodes[face.a].position;
    const pB = model.nodes[face.b].position;
    const pC = model.nodes[face.c].position;
    const n = normalize(cross(sub(pB, pA), sub(pC, pA)));
    lines.push(`vn ${n.x.toFixed(4)} ${n.y.toFixed(4)} ${n.z.toFixed(4)}`);
  }
  lines.push("");

  // Group: Faces
  lines.push("g Dome_Faces");
  let normalIdx = 1;
  for (const face of model.faces) {
    const a = face.a + 1;
    const b = face.b + 1;
    const c = face.c + 1;
    lines.push(`f ${a}//${normalIdx} ${b}//${normalIdx} ${c}//${normalIdx}`);
    normalIdx++;
  }

  // Also include polyline struts as lines
  lines.push("");
  lines.push("g Dome_Beams");
  for (const edge of model.edges) {
    lines.push(`l ${edge.start + 1} ${edge.end + 1}`);
  }

  return lines.join("\n");
}
